### ISSUE TITLE
Null types

### ISSUE THREAD

**Issue by dafanasev1986** [twpayne/pgx-geom#1]
Currently codec does not support scans of possible null geometries (returns the EOF error).

As a workaround I added this piece of code, but in this case we loose the ability to have non null geometries
(although it should be restricted on the DB side anyway).
```
func (p binaryScanPlan) Scan(src []byte, target any) error {
        ...
	if src == nil {
		return nil
	}
```
If you are ok with this sollution please add it, or maybe there is a better one (e.g. separate type like  NullGeometry)?

**Comment by twpayne** [comment]
> Currently codec does not support scans of possible null geometries (returns the EOF error).

I tried to duplicate this problem in #2, but as far as I can tell the current code supports converting `NULL` geometries to Go's `nil` correctly.

Could you give an example or test case that demonstrates the problem? I would be very happy to fix this.

**Comment by dafanasev1986** [comment]
Of course, here is an example

```
func TestCodecDecodeNullGeometry(t *testing.T) {
	defaultConnTestRunner.RunTest(context.Background(), t, func(ctx context.Context, tb testing.TB, conn *pgx.Conn) {
		type s struct {
			Geom geom.T `db:"geom"`
		}

		tb.Helper()
		rows, err := conn.Query(ctx, "select NULL::geometry AS geom", pgx.QueryResultFormats{pgx.BinaryFormatCode})
		assert.NoError(tb, err)

		value, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[s])
		assert.NoError(t, err)
		assert.NotZero(t, value)
		assert.Zero(t, value.Geom)
	})
}
```

**Comment by twpayne** [comment]
Thank you for the example. I don't think the test is correct. Specifically, this line:

```go
assert.NotZero(t, value)
```

`value` is an interface type. I believe that pgx-geom is correctly setting the underlying value to `nil` and that this test is incorrectly testing for a `nil` interface. For more information, see https://groups.google.com/g/golang-nuts/c/wnH302gBa4I.

**Comment by dafanasev1986** [comment]
I'm sorry, my fault, you can all remove all asserts except the one that tests for the error (assert.NoError(t, err)). The test will still fail

**Comment by twpayne** [comment]
Thank you for the extra information. I've added support for NULL geometries in #2 and tagged version `v0.0.1` which includes the fix.

**Comment by dafanasev1986** [comment]
Thank you!

**Comment by elefantepequeno** [comment]
@twpayne, I'm using `github.com/twpayne/pgx-geom v0.0.2` with `github.com/twpayne/go-geom v1.6.1` and still getting EOF error when attempting to scan `NULL` value.
Column is defined as `coordinates GEOGRAPHY(POINT, 4326)`.

The only relevant part of a trace:
```
github.com/jackc/pgx/v5.(*baseRows).Close
	/root/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.5/rows.go:189
github.com/jackc/pgx/v5.(*baseRows).fatal
	/root/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.5/rows.go:220
github.com/jackc/pgx/v5.(*baseRows).Scan
	/root/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.5/rows.go:287
github.com/jackc/pgx/v5.(*connRow).Scan
	/root/go/pkg/mod/github.com/jackc/pgx/v5@v5.7.5/rows.go:119
```

I assume scanner returned an error here: https://github.com/jackc/pgx/blob/v5.7.5/rows.go#L284
Not sure how to get details.

**Comment by elefantepequeno** [comment]
I beleive [DecodeValue](https://github.com/twpayne/pgx-geom/blob/master/pgxgeom.go#L223) is returning `EOF` before scanner is called.

This seems to solve the issue:
```diff
func (c codec) DecodeValue(m *pgtype.Map, oid uint32, format int16, src []byte) (any, error) {
+	if len(src) == 0 {
+		return nil, nil
+	}

	switch format {
```

**Comment by elefantepequeno** [comment]
Oh, the problem is `sqlc` generates this column as `interface{}` and not as `geom.T`. I've reproduced this in a test, will try to make PR with a fix today.
